### PR TITLE
[Feat]: Abiwan V2 Integration

### PR DESCRIPTION
**Pull request by haroune-mohammedi**
## Motivation and Resolution
Cairo v1 introduced many breaking changes to the ABI, this PR aims to integrate abiwan v2 which support the new cairo versions with starknet.js

## Usage related changes

Users will be able to get typed function calls on their Cairo v1 contracts, all they need to do is call the `typedv2` function and pass the ABI object

## Checklist:

- [x] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Comment by haroune-mohammedi** [comment]
Closes #877

**Comment by haroune-mohammedi** [comment]
Related to https://github.com/keep-starknet-strange/abi-wan-kanabi/pull/51

**Review by fracek — APPROVED** [review]

**Review by tabaktoni — APPROVED** [review]
LGTM ⚡🚀

**Review by ivpavici — APPROVED** [review]

**Comment by ivpavici** [comment]
Documentation and guides will be modified in another PR.
Also, we should port this PR in v6 cc @tabaktoni

**Pull request merged**
