### PR TITLE
feat: add optional fallbackNodeUrls property to RpcProvider

### PR DESCRIPTION
**Pull request by jereldlimjy**
## Motivation and Resolution

Solve issue #872

## Usage related changes

...

## Development related changes

...

## Checklist:

- [X] Performed a self-review of the code
- [X] Rebased to the last commit of the target branch (or merged it into my branch)
- [X] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

### CODE REVIEW

**Review by penovicp — CHANGES_REQUESTED** [review]
There is a notable change with the `channel/provider` split in the upcoming v6 version that relates to how underlying requests are made, so adding this feature should be based on and the PR should target the `beta` branch.

**Comment by eliotstock** [comment]
@penovicp, we'd love to use this quite soon in some downstream dApps.

When do you see v6 being released?

Could we do a v5 version in parallel, do you think?

**Comment by ivpavici** [comment]
hello!

I want to clarify the steps for this PR!
First, @eliotstock you would like this PR to be included into Starknet.js v5? If that is the case, it's possible!
Second, for Sn.js v6, @jereldlimjy should modify it a bit and target the `beta` branch, do you want to do it?

Also, adding a test would be awesome!

**Comment by penovicp** [comment]
Superseded by #980

**Pull request closed without merging**
