### PR TITLE
Update deployFee estimation example

### PR DESCRIPTION
**Pull request by petscheit**
Before it seemed like the calldata cost would be derived via contact ABI automatically, this makes it more clear that the constructor calldata must be explicitly passed

### CODE REVIEW

**Comment by PhilippeR26** [comment]
Hello,
In fact, the `constructorCalldata` is not mandatory :
image
The current doc is valid for a contract without constructor, and is not showing that it's necessary in case of constructor.
Your proposal do not show that it's not necessary in case of contract without constructor.

Could you add a comment? Like :

> `constructorCalldata` is not necessary if the contract to deploy as no constructor.

**Comment by petscheit** [comment]
Hi Phillipe,
I was chasing an issue where the gas estimation for deployment was way too low and it took me a moment to figure out what is causing this. My assumption was that the estimation would fetch the constructor arguments from the contracts ABI, and adds this to the estimate. Having this in the example would have saved me a bit of investigating. 

I also see you point though, maybe it can be made a clearer in another way in the docs.

**Comment by PhilippeR26** [comment]
Just insert in your PR this comment : 

> `constructorCalldata` is not necessary if the contract to deploy has no constructor.

**Review by tabaktoni — CHANGES_REQUESTED** [review]
@PhilippeR26 suggestion

**Comment by PhilippeR26** [comment]
> @PhilippeR26 suggestion

Yes, as I wrote earlier, I would like to add just after the code : 

> `constructorCalldata` is not necessary if the contract to deploy has no constructor.

**Pull request merged**
