### PR TITLE
docs: walletAccount - add details for chainId

### PR DESCRIPTION
**Pull request by PhilippeR26**
## Motivation and Resolution
Following a suggestion of @tabaktoni , the guide of `WalletAccount` has been updated, to add explanation about `chainId`.

## Usage related changes
N/A

## Development related changes
N/A

## Checklist:
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] All tests are passing

### CODE REVIEW

**Comment by tabaktoni** [comment]
Should we add `requestChainId` to WalletAccount class?
Also `deploymentData` and `supportedSpecs` are not there I can't remember why.

**Comment by PhilippeR26** [comment]
We have also to solve item 2 of https://github.com/starknet-io/types-js/issues/20

**Comment by PhilippeR26** [comment]
> Should we add `requestChainId` to WalletAccount class? 

Seems not mandatory, but if we do it, it will be necessary to use a method name that explains that the response is about the wallet (not the account).

**Comment by tabaktoni** [comment]
> We have also to solve item 2 of [starknet-io/types-js#20](https://github.com/starknet-io/types-js/issues/20)

Resolved

**Comment by PhilippeR26** [comment]
Nice. Now, just need a new version of the lib.

**Pull request merged**
