### PR TITLE
feat: add optional fallbackNodeUrls property to RpcProvider

### PR DESCRIPTION
**Pull request by piwonskp**
## Motivation and Resolution
Solve issue #872. The PR replaces #905. PR targetting v6: #953 

### RPC version (if applicable)

...

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Review by penovicp — CHANGES_REQUESTED** [review]
There should be a discussion about the design for this feature. The main issue I see with this approach is that by being applied after the error handler the fallback would also take effect for expected error responses, e.g. a response with HTTP status `200` that contains a `Transaction hash not found` error, which doesn't feel right to me.

**Comment by tabaktoni** [comment]
@piwonskp Will you update for expected error responses?

**Comment by piwonskp** [comment]
@tabaktoni @penovicp  Sure, I'll narrow down error handling to fetch errors

**Comment by piwonskp** [comment]
@tabaktoni @penovicp Done, rpc error handling is done outside of the catch clause now

**Pull request closed without merging**
