### PR TITLE
 fix handling of negative i128 values in encodeValue 

### PR DESCRIPTION
**Pull request by developerfred**
## Motivation and Resolution

fix the bug #1004

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Review by tabaktoni — APPROVED** [review]
lgtm

**Comment by ivpavici** [comment]
I would still wait for Petar to come back and TAL

**Comment by penovicp** [comment]
`i128` handling has been fixed since [v6.6.6](https://github.com/starknet-io/starknet.js/releases/tag/v6.6.6), the corresponding issue #1004 was accidentally left open since the relevant PR also addressed the related #1002.

The negative value shift being introduced here is already done [within the encodeValue function](https://github.com/starknet-io/starknet.js/blob/v6.8.0/src/utils/typedData.ts#L328). Also, the [Starknet docs](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/serialization_of_Cairo_types/#data_types_of_252_bits_or_less) define that the shift base for serialization should be the Starknet prime.

**Comment by tabaktoni** [comment]
In that case, we must close it @ivpavici

**Comment by ivpavici** [comment]
@developerfred I'll send you a small reward on OnlyDust for your time! Thanks!

**Comment by ivpavici** [comment]
"@developerfred isn't on OnlyDust. You can still reward them. They'll need to create an account and sync it with their GitHub handle to claim it."

**Pull request closed without merging**
