### PR TITLE
fix: export abi types

### PR DESCRIPTION
**Pull request by tabaktoni**
## Motivation and Resolution

...

### RPC version (if applicable)

...

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

### CODE REVIEW

**Review by PhilippeR26 — COMMENTED** [review]
Seems that rpc spec 0.6 is identical to rpc spec 0.7 about contract types.
In this case, for any src/utils code , is it better to use the internal rpcspec_06, or to use the rpcspec 0.7 of the types-js library?

**Comment by tabaktoni** [comment]
> Seems that rpc spec 0.6 is identical to rpc spec 0.7 about contract types. In this case, for any src/utils code , is it better to use the internal rpcspec_06, or to use the rpcspec 0.7 of the types-js library?

Yea, abi didn't change, I would recommend using rpcspec 0.7  as it is the latest one, and 0.6 will be deprecated at some point.

**Comment by PhilippeR26** [comment]
So, you should also add exports to these functions in the types-js lib.

**Comment by tabaktoni** [comment]
> So, you should also add exports to these functions in the types-js lib.

Yes it is added

**Pull request merged**
