### PR TITLE
Cairo 2.4.0 new types : bytes31 & ByteArray

### PR DESCRIPTION
**Pull request by PhilippeR26**
## Motivation and Resolution
implement issue #886 

## Usage related changes

For older Cairo versions, the default response of` CallData.compile("fghdfghdfghdfghdfghfdghfgsdfgsdfgsdfgsdfg)` is modified. It's now necessary to use : `CallData.compile(shortString.splitLongString("gfddfghdfhdfghdfghdfghfdghdfghgfh");` to have an array of felts.

For Cairo 2.4.0, the result of CallData.compile("fghdfghdfghdfghdfghfdghfgsdfgsdfgsdfgsdfg)` is a serialized ByteArray

(see last message in the issue : https://github.com/starknet-io/starknet.js/issues/886#issuecomment-1850617944)

## Development related changes
Added handling of Cairo  `bytes31` and `ByteArray` types.

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Comment by PhilippeR26** [comment]
tests where OK in Beta3.
In Beta 6, it seems that `rpcProvider.test.ts` is in an infinite loop.

**Comment by tabaktoni** [comment]
> tests were OK in Beta3. In Beta 6, it seems that `rpcProvider.test.ts` is in an infinite loop.

Yes, Fixed

**Comment by tabaktoni** [comment]
I would open discussion regarding this I don't think we should do it this way.
1. I want to eradicate the naive approach and leave it only for backward compatibility.
Also including last abi one call.

**Comment by haroune-mohammedi** [comment]
Let's not merge this PR until we add typed tests since abiwan support latest cairo version too as per https://github.com/keep-starknet-strange/abi-wan-kanabi/pull/63

**Review by tabaktoni — APPROVED** [review]
Solution is lgtm, we should rethink how we handle Cairo types in js later on

**Pull request merged**
