### PR TITLE
refactor: update starknetid contract addr on sepolia & remove old code

### PR DESCRIPTION
**Pull request by irisdv**
## Motivation and Resolution

This PR updates starknet ID contract addresses on Sepolia, and remove some code that was needed to ensure a smooth transition on a change we made to the `address_to_domain` function in the naming contract.

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Comment by PhilippeR26** [comment]
Hello,
This PR will create conflicts with #1133

**Comment by irisdv** [comment]
Should I base my PR on another branch then ?

**Comment by PhilippeR26** [comment]
As it has been already reviewed, I think that PR#1133 will be merged soon by @ivpavici  or @tabaktoni , in `next-version` branch.
You will have to use this branch as base, if necessary adapt your JSDOC to be in accordance with our new standard (100% with example), and propose your PR in `next-branch`

**Comment by irisdv** [comment]
Closing this as I opened a new PR https://github.com/starknet-io/starknet.js/pull/1139 based on `next-version`, once that I'll update once PR#1133 was merged.

**Comment by ivpavici** [comment]
@irisdv hi and thanks! merged @PhilippeR26 's PR :)

**Pull request closed without merging**
