### PR TITLE
Add search functionnality to the official website.

### PR DESCRIPTION
**Pull request by PhilippeR26**
## Motivation and Resolution
Solve #875.
Add  a search tool in the top bar of the Starknet.js website.

## Usage related changes
image

## Development related changes

As requested by @ivpavici , temporarily, I used my Algolia account to add the search functionality.
`docusaurus.config.js` includes the Algolia keys.
Bump versions of docusaurus and plugins (new version needs an empty `@example` line)
This functionality has been tested in my fork : https://philipper26.github.io/starknet.js/ 
## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves

### CODE REVIEW

**Review by ivpavici — APPROVED** [review]
If it's safe to add appId and apiKey like this, then LGTM! thanks :)

**Comment by ivpavici** [comment]
@PhilippeR26 maybe we should target `develop` branch as well!

**Comment by PhilippeR26** [comment]
Not sure how to proceed to merge in 2 branches.

**Comment by PhilippeR26** [comment]
> If it's safe to add appId and apiKey like this, then LGTM! thanks :)

No problem ; it's only useful for this site.

**Review by tabaktoni — APPROVED** [review]
LGTM

**Pull request merged**
